// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repoctlsvc.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	repoctlsvc.proto

It has these top-level messages:
	NewSiteRequest
	NewSiteReply
	DeleteSiteRequest
	DeleteSiteReply
	NewPostRequest
	NewPostReply
	DeletePostRequest
	DeletePostReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewSiteRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
}

func (m *NewSiteRequest) Reset()                    { *m = NewSiteRequest{} }
func (m *NewSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*NewSiteRequest) ProtoMessage()               {}
func (*NewSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewSiteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewSiteRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

type NewSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *NewSiteReply) Reset()                    { *m = NewSiteReply{} }
func (m *NewSiteReply) String() string            { return proto.CompactTextString(m) }
func (*NewSiteReply) ProtoMessage()               {}
func (*NewSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteSiteRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
}

func (m *DeleteSiteRequest) Reset()                    { *m = DeleteSiteRequest{} }
func (m *DeleteSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSiteRequest) ProtoMessage()               {}
func (*DeleteSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteSiteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DeleteSiteRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

type DeleteSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteSiteReply) Reset()                    { *m = DeleteSiteReply{} }
func (m *DeleteSiteReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteSiteReply) ProtoMessage()               {}
func (*DeleteSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type NewPostRequest struct {
	Author   string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *NewPostRequest) Reset()                    { *m = NewPostRequest{} }
func (m *NewPostRequest) String() string            { return proto.CompactTextString(m) }
func (*NewPostRequest) ProtoMessage()               {}
func (*NewPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NewPostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *NewPostRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

func (m *NewPostRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *NewPostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewPostReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *NewPostReply) Reset()                    { *m = NewPostReply{} }
func (m *NewPostReply) String() string            { return proto.CompactTextString(m) }
func (*NewPostReply) ProtoMessage()               {}
func (*NewPostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NewPostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeletePostRequest struct {
	Author   string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
}

func (m *DeletePostRequest) Reset()                    { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()               {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeletePostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *DeletePostRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

func (m *DeletePostRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type DeletePostReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeletePostReply) Reset()                    { *m = DeletePostReply{} }
func (m *DeletePostReply) String() string            { return proto.CompactTextString(m) }
func (*DeletePostReply) ProtoMessage()               {}
func (*DeletePostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeletePostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*NewSiteRequest)(nil), "pb.NewSiteRequest")
	proto.RegisterType((*NewSiteReply)(nil), "pb.NewSiteReply")
	proto.RegisterType((*DeleteSiteRequest)(nil), "pb.DeleteSiteRequest")
	proto.RegisterType((*DeleteSiteReply)(nil), "pb.DeleteSiteReply")
	proto.RegisterType((*NewPostRequest)(nil), "pb.NewPostRequest")
	proto.RegisterType((*NewPostReply)(nil), "pb.NewPostReply")
	proto.RegisterType((*DeletePostRequest)(nil), "pb.DeletePostRequest")
	proto.RegisterType((*DeletePostReply)(nil), "pb.DeletePostReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Repoctl service

type RepoctlClient interface {
	NewSite(ctx context.Context, in *NewSiteRequest, opts ...grpc.CallOption) (*NewSiteReply, error)
	DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteReply, error)
	NewPost(ctx context.Context, in *NewPostRequest, opts ...grpc.CallOption) (*NewPostReply, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostReply, error)
}

type repoctlClient struct {
	cc *grpc.ClientConn
}

func NewRepoctlClient(cc *grpc.ClientConn) RepoctlClient {
	return &repoctlClient{cc}
}

func (c *repoctlClient) NewSite(ctx context.Context, in *NewSiteRequest, opts ...grpc.CallOption) (*NewSiteReply, error) {
	out := new(NewSiteReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/NewSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteReply, error) {
	out := new(DeleteSiteReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/DeleteSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) NewPost(ctx context.Context, in *NewPostRequest, opts ...grpc.CallOption) (*NewPostReply, error) {
	out := new(NewPostReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/NewPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostReply, error) {
	out := new(DeletePostReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/DeletePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Repoctl service

type RepoctlServer interface {
	NewSite(context.Context, *NewSiteRequest) (*NewSiteReply, error)
	DeleteSite(context.Context, *DeleteSiteRequest) (*DeleteSiteReply, error)
	NewPost(context.Context, *NewPostRequest) (*NewPostReply, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error)
}

func RegisterRepoctlServer(s *grpc.Server, srv RepoctlServer) {
	s.RegisterService(&_Repoctl_serviceDesc, srv)
}

func _Repoctl_NewSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).NewSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/NewSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).NewSite(ctx, req.(*NewSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/DeleteSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).DeleteSite(ctx, req.(*DeleteSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_NewPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).NewPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/NewPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).NewPost(ctx, req.(*NewPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repoctl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Repoctl",
	HandlerType: (*RepoctlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSite",
			Handler:    _Repoctl_NewSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _Repoctl_DeleteSite_Handler,
		},
		{
			MethodName: "NewPost",
			Handler:    _Repoctl_NewPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Repoctl_DeletePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repoctlsvc.proto",
}

func init() { proto.RegisterFile("repoctlsvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xff, 0xb4, 0x3f, 0x0d, 0x8c, 0x10, 0x84, 0x29, 0xa0, 0x28, 0xab, 0x2a, 0x6c, 0x58,
	0x45, 0x02, 0x76, 0x2c, 0x11, 0x6c, 0x11, 0x0a, 0x27, 0x48, 0xa2, 0x41, 0x44, 0x72, 0x63, 0x93,
	0x4c, 0x41, 0xe5, 0xc2, 0x5c, 0x03, 0xc5, 0x8e, 0x5d, 0xb7, 0x54, 0xdd, 0x20, 0x76, 0x19, 0x3f,
	0x3f, 0x7f, 0x2f, 0x33, 0x03, 0x51, 0x4b, 0x4a, 0x56, 0x2c, 0xba, 0xf7, 0x2a, 0x53, 0xad, 0x64,
	0x89, 0x23, 0x55, 0xa6, 0x77, 0x70, 0xf4, 0x48, 0x1f, 0xcf, 0x35, 0x53, 0x4e, 0x6f, 0x0b, 0xea,
	0x18, 0x4f, 0x61, 0x8f, 0xe6, 0x45, 0x2d, 0xe2, 0x60, 0x16, 0x5c, 0x1e, 0xe4, 0xa6, 0xc0, 0x04,
	0xf6, 0xbb, 0x9a, 0xa9, 0x29, 0xe6, 0x14, 0x8f, 0xb4, 0xe0, 0xea, 0x74, 0x06, 0x87, 0xee, 0x0d,
	0x25, 0x96, 0x18, 0xc1, 0x98, 0xda, 0x76, 0xf0, 0xf7, 0x9f, 0xe9, 0x03, 0x9c, 0xdc, 0x93, 0x20,
	0xa6, 0xdf, 0x81, 0x2e, 0xe0, 0xd8, 0x7f, 0x66, 0x3b, 0xeb, 0x53, 0xff, 0xd1, 0x93, 0xec, 0xd8,
	0x82, 0xce, 0x61, 0x52, 0x2c, 0xf8, 0x55, 0xda, 0x6b, 0x43, 0xb5, 0x0b, 0xd5, 0x6b, 0x2f, 0xb5,
	0x30, 0xda, 0xd8, 0x68, 0xb6, 0xc6, 0x18, 0xc2, 0x4a, 0x36, 0x4c, 0x0d, 0xc7, 0xff, 0xb5, 0x64,
	0xcb, 0xa1, 0x13, 0x86, 0xbd, 0x3d, 0x5d, 0x65, 0x3b, 0xf1, 0x87, 0x01, 0x57, 0x7d, 0xda, 0x91,
	0xe4, 0xfa, 0x2b, 0x80, 0x30, 0x37, 0x2b, 0x81, 0x57, 0x10, 0x0e, 0x13, 0x44, 0xcc, 0x54, 0x99,
	0xad, 0xaf, 0x44, 0x12, 0xad, 0x9d, 0x29, 0xb1, 0x4c, 0xff, 0xe1, 0x2d, 0xc0, 0x6a, 0x16, 0x78,
	0xd6, 0xdf, 0xf8, 0x31, 0xe2, 0x64, 0xba, 0x79, 0x6c, 0xbc, 0x06, 0xd7, 0x87, 0x73, 0x38, 0xaf,
	0x1d, 0x0e, 0xe7, 0xd2, 0xfb, 0x38, 0xed, 0xf2, 0x70, 0xbe, 0x71, 0xba, 0x79, 0xac, 0xbd, 0xe5,
	0x44, 0xaf, 0xfb, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xef, 0x2a, 0x80, 0x02, 0x03,
	0x00, 0x00,
}
