// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repoctlsvc.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	repoctlsvc.proto

It has these top-level messages:
	NewSiteRequest
	NewSiteReply
	DeleteSiteRequest
	DeleteSiteReply
	WritePostRequest
	WritePostReply
	RemovePostRequest
	RemovePostReply
	ReadPostRequest
	ReadPostReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewSiteRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
}

func (m *NewSiteRequest) Reset()                    { *m = NewSiteRequest{} }
func (m *NewSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*NewSiteRequest) ProtoMessage()               {}
func (*NewSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewSiteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewSiteRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

type NewSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *NewSiteReply) Reset()                    { *m = NewSiteReply{} }
func (m *NewSiteReply) String() string            { return proto.CompactTextString(m) }
func (*NewSiteReply) ProtoMessage()               {}
func (*NewSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteSiteRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
}

func (m *DeleteSiteRequest) Reset()                    { *m = DeleteSiteRequest{} }
func (m *DeleteSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSiteRequest) ProtoMessage()               {}
func (*DeleteSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteSiteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DeleteSiteRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

type DeleteSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteSiteReply) Reset()                    { *m = DeleteSiteReply{} }
func (m *DeleteSiteReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteSiteReply) ProtoMessage()               {}
func (*DeleteSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type WritePostRequest struct {
	Author   string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *WritePostRequest) Reset()                    { *m = WritePostRequest{} }
func (m *WritePostRequest) String() string            { return proto.CompactTextString(m) }
func (*WritePostRequest) ProtoMessage()               {}
func (*WritePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WritePostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *WritePostRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

func (m *WritePostRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *WritePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WritePostReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *WritePostReply) Reset()                    { *m = WritePostReply{} }
func (m *WritePostReply) String() string            { return proto.CompactTextString(m) }
func (*WritePostReply) ProtoMessage()               {}
func (*WritePostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WritePostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RemovePostRequest struct {
	Author   string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
}

func (m *RemovePostRequest) Reset()                    { *m = RemovePostRequest{} }
func (m *RemovePostRequest) String() string            { return proto.CompactTextString(m) }
func (*RemovePostRequest) ProtoMessage()               {}
func (*RemovePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemovePostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *RemovePostRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

func (m *RemovePostRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type RemovePostReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *RemovePostReply) Reset()                    { *m = RemovePostReply{} }
func (m *RemovePostReply) String() string            { return proto.CompactTextString(m) }
func (*RemovePostReply) ProtoMessage()               {}
func (*RemovePostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemovePostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ReadPostRequest struct {
	Author   string `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
}

func (m *ReadPostRequest) Reset()                    { *m = ReadPostRequest{} }
func (m *ReadPostRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadPostRequest) ProtoMessage()               {}
func (*ReadPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadPostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ReadPostRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

func (m *ReadPostRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type ReadPostReply struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *ReadPostReply) Reset()                    { *m = ReadPostReply{} }
func (m *ReadPostReply) String() string            { return proto.CompactTextString(m) }
func (*ReadPostReply) ProtoMessage()               {}
func (*ReadPostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReadPostReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReadPostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*NewSiteRequest)(nil), "pb.NewSiteRequest")
	proto.RegisterType((*NewSiteReply)(nil), "pb.NewSiteReply")
	proto.RegisterType((*DeleteSiteRequest)(nil), "pb.DeleteSiteRequest")
	proto.RegisterType((*DeleteSiteReply)(nil), "pb.DeleteSiteReply")
	proto.RegisterType((*WritePostRequest)(nil), "pb.WritePostRequest")
	proto.RegisterType((*WritePostReply)(nil), "pb.WritePostReply")
	proto.RegisterType((*RemovePostRequest)(nil), "pb.RemovePostRequest")
	proto.RegisterType((*RemovePostReply)(nil), "pb.RemovePostReply")
	proto.RegisterType((*ReadPostRequest)(nil), "pb.ReadPostRequest")
	proto.RegisterType((*ReadPostReply)(nil), "pb.ReadPostReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Repoctl service

type RepoctlClient interface {
	NewSite(ctx context.Context, in *NewSiteRequest, opts ...grpc.CallOption) (*NewSiteReply, error)
	DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteReply, error)
	WritePost(ctx context.Context, in *WritePostRequest, opts ...grpc.CallOption) (*WritePostReply, error)
	RemovePost(ctx context.Context, in *RemovePostRequest, opts ...grpc.CallOption) (*RemovePostReply, error)
	ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostReply, error)
}

type repoctlClient struct {
	cc *grpc.ClientConn
}

func NewRepoctlClient(cc *grpc.ClientConn) RepoctlClient {
	return &repoctlClient{cc}
}

func (c *repoctlClient) NewSite(ctx context.Context, in *NewSiteRequest, opts ...grpc.CallOption) (*NewSiteReply, error) {
	out := new(NewSiteReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/NewSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...grpc.CallOption) (*DeleteSiteReply, error) {
	out := new(DeleteSiteReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/DeleteSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) WritePost(ctx context.Context, in *WritePostRequest, opts ...grpc.CallOption) (*WritePostReply, error) {
	out := new(WritePostReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/WritePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) RemovePost(ctx context.Context, in *RemovePostRequest, opts ...grpc.CallOption) (*RemovePostReply, error) {
	out := new(RemovePostReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/RemovePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoctlClient) ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostReply, error) {
	out := new(ReadPostReply)
	err := grpc.Invoke(ctx, "/pb.Repoctl/ReadPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Repoctl service

type RepoctlServer interface {
	NewSite(context.Context, *NewSiteRequest) (*NewSiteReply, error)
	DeleteSite(context.Context, *DeleteSiteRequest) (*DeleteSiteReply, error)
	WritePost(context.Context, *WritePostRequest) (*WritePostReply, error)
	RemovePost(context.Context, *RemovePostRequest) (*RemovePostReply, error)
	ReadPost(context.Context, *ReadPostRequest) (*ReadPostReply, error)
}

func RegisterRepoctlServer(s *grpc.Server, srv RepoctlServer) {
	s.RegisterService(&_Repoctl_serviceDesc, srv)
}

func _Repoctl_NewSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).NewSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/NewSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).NewSite(ctx, req.(*NewSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/DeleteSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).DeleteSite(ctx, req.(*DeleteSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_WritePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).WritePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/WritePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).WritePost(ctx, req.(*WritePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_RemovePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).RemovePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/RemovePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).RemovePost(ctx, req.(*RemovePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repoctl_ReadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoctlServer).ReadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Repoctl/ReadPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoctlServer).ReadPost(ctx, req.(*ReadPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repoctl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Repoctl",
	HandlerType: (*RepoctlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSite",
			Handler:    _Repoctl_NewSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _Repoctl_DeleteSite_Handler,
		},
		{
			MethodName: "WritePost",
			Handler:    _Repoctl_WritePost_Handler,
		},
		{
			MethodName: "RemovePost",
			Handler:    _Repoctl_RemovePost_Handler,
		},
		{
			MethodName: "ReadPost",
			Handler:    _Repoctl_ReadPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repoctlsvc.proto",
}

func init() { proto.RegisterFile("repoctlsvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0xc7, 0xdb, 0x54, 0xfb, 0x18, 0xb4, 0xa6, 0x63, 0x95, 0x90, 0x53, 0x59, 0x2f, 0x9e, 0x0a,
	0x3e, 0x40, 0xd0, 0x9b, 0xe8, 0x55, 0x24, 0x1e, 0x3c, 0xa7, 0x71, 0xc4, 0xc0, 0xb6, 0xbb, 0x26,
	0xdb, 0x4a, 0xc1, 0x6f, 0xe3, 0x17, 0x95, 0xcd, 0x66, 0xd3, 0x24, 0x0d, 0x5e, 0xa4, 0xb7, 0xcc,
	0x6b, 0x7f, 0x7f, 0x66, 0xfe, 0x01, 0x37, 0x21, 0x29, 0x22, 0xc5, 0xd3, 0x55, 0x34, 0x95, 0x89,
	0x50, 0x02, 0x1d, 0x39, 0x63, 0xf7, 0x30, 0x7c, 0xa2, 0xaf, 0x97, 0x58, 0x51, 0x40, 0x9f, 0x4b,
	0x4a, 0x15, 0x8e, 0x61, 0x9f, 0xe6, 0x61, 0xcc, 0xbd, 0xf6, 0xa4, 0x7d, 0x3e, 0x08, 0x4c, 0x80,
	0x3e, 0xf4, 0xd3, 0x58, 0xd1, 0x22, 0x9c, 0x93, 0xe7, 0x64, 0x85, 0x22, 0x66, 0x13, 0x38, 0x28,
	0xde, 0x90, 0x7c, 0x8d, 0x2e, 0x74, 0x28, 0x49, 0xf2, 0x79, 0xfd, 0xc9, 0x1e, 0x61, 0xf4, 0x40,
	0x9c, 0x14, 0xfd, 0x0f, 0x74, 0x06, 0x47, 0xe5, 0x67, 0x9a, 0x59, 0xdf, 0xe0, 0xbe, 0x26, 0xb1,
	0xa2, 0x67, 0x91, 0x2a, 0x8b, 0x3a, 0x85, 0x6e, 0xb8, 0x54, 0x1f, 0xc2, 0x36, 0xe6, 0xd1, 0x5f,
	0x30, 0x5d, 0x7b, 0x8f, 0xb9, 0xa9, 0x75, 0x4c, 0xcd, 0xc6, 0xe8, 0x41, 0x2f, 0x12, 0x0b, 0x45,
	0x0b, 0xe5, 0xed, 0x65, 0x25, 0x1b, 0x32, 0x06, 0xc3, 0x12, 0xbd, 0x59, 0x61, 0x04, 0xa3, 0x80,
	0xe6, 0x62, 0xb5, 0x4b, 0x89, 0x7a, 0x57, 0x65, 0x48, 0xb3, 0x92, 0x50, 0x37, 0x85, 0x6f, 0xbb,
	0xd4, 0x71, 0x07, 0x87, 0x1b, 0x84, 0x56, 0x51, 0xda, 0x5d, 0xbb, 0xb2, 0x3b, 0xab, 0xcf, 0x29,
	0xf4, 0x5d, 0xfe, 0x38, 0xd0, 0x0b, 0x8c, 0x6d, 0xf1, 0x02, 0x7a, 0xb9, 0xcb, 0x10, 0xa7, 0x72,
	0x36, 0xad, 0xda, 0xd6, 0x77, 0x2b, 0x39, 0xc9, 0xd7, 0xac, 0x85, 0xb7, 0x00, 0x1b, 0xbf, 0xe0,
	0x89, 0xee, 0xd8, 0xb2, 0xa1, 0x7f, 0x5c, 0x4f, 0x9b, 0xd9, 0x1b, 0x18, 0x14, 0x87, 0xc4, 0xb1,
	0xee, 0xa9, 0xbb, 0xca, 0xc7, 0x5a, 0xb6, 0x80, 0x6e, 0x16, 0x6f, 0xa0, 0x5b, 0xd7, 0x36, 0xd0,
	0xda, 0x7d, 0x58, 0x0b, 0xaf, 0xa1, 0x6f, 0x97, 0x85, 0x79, 0x4b, 0xe5, 0x3a, 0xfe, 0xa8, 0x9a,
	0xcc, 0xa6, 0x66, 0xdd, 0xec, 0x77, 0xbe, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x67, 0x49, 0x52,
	0xa2, 0xe2, 0x03, 0x00, 0x00,
}
